sensor:
  - platform: adc
    pin: GPIO34
    name: "Bodenfeuchte Sensor 1"
    id: feuchte_1
    update_interval: 10s
    filters:
      - calibrate_linear:
          - 0.3 -> 100.0
          - 2.5 -> 0.0
